{"uuid": "c3051af5-0904-4b07-adcb-38806c58ecf1", "children": ["0ceff682-3eed-45c5-92e1-e7aca9e95711"], "befores": [{"name": "_xunit_setup_method_fixture_TestCarcenter", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017794BECD00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"D:\\software\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\software\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\software\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\software\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\software\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"E:\\DM\\ShirleyPytest\\scripts\\test01_carcenter.py\", line 17, in setup_method\n    self.driver = init_driver()\n  File \"E:\\DM\\ShirleyPytest\\base\\base_driver.py\", line 16, in init_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723\", caps)\n  File \"D:\\software\\Python310\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 257, in __init__\n    super().__init__(\n  File \"D:\\software\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"D:\\software\\Python310\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 346, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"D:\\software\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\software\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 297, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\software\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 318, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 118, in request\n    return self.request_encode_body(\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 217, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n  File \"D:\\software\\Python310\\lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1699841842295, "stop": 1699841850464}], "start": 1699841842295, "stop": 1699841850614}